services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: masso
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5430:5432"

  app-dev:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    volumes:
      - .:/app
    command: sh -c "npx prisma migrate dev && npm run dev"

  app:
    profiles: ["prod"]
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production
    env_file:
      - .env.docker
    command: sh -c "npm run start"

volumes:
  postgres_data: